name: Release on tag

on:
  push:
    tags:
      - v**

jobs:
  # build-docker-image:
  #   name: Build docker image
  #   uses: ./.github/workflows/docker.yml
  #   secrets: inherit

  create-release:
    name: Create release
    #needs: [build-docker-image]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout documentation
        uses: actions/checkout@v3
        with:
          ref: "main"
          fetch-depth: 0

      - name: Push main to production
        run: |
          git fetch origin production
          git push origin main:production

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          # create a draft release which needs manual approval
          draft: true
